ruby_version: 2.5.0
fix: true
parallel: true
ignore:
  - 'lib/sidekiq/delay_extensions/**/*':
    - Style/MissingRespondToMissing
  - '**/*':
    - Lint/RescueException
    - Security/YAMLLoad
    - Style/GlobalVars
